import sys
from tkinter import *
import tkinter as tk
#25.7.2023
def exit():
	sys.exit(0)


seznam = ['BTCUSD','BTCEUR','BTCGBP','BTCPAX','GBPUSD','GBPEUR','EURUSD','XRPUSD','XRPEUR'
				 ,'XRPGBP','LTCUSD','LTCEUR','LTCGBP','ETHUSD','ETHEUR',
				 'ETHGBP','BCHUSD','BCHEUR','PAXUSD','XLMUSD',
				 'XLMGBP','LINKUSD','LINKEUR','LINKGBP','OMGUSD','OMGEUR','OMGGBP',
				 'USDCUSD','USDCEUR','AAVEUSD','AAVEEUR',
				 'BATUSD','BATEUR','UMAUSD','UMAEUR','DAIUSD','KNCUSD','KNCEUR','MKRUSD',
				 'ZRXUSD','ZRXEUR','GUSDUSD','ALGOUSD','ALGOEUR','AUDIOUSD'
				 ,'CRVUSD','CRVEUR','SNXUSD','SNXEUR','UNIUSD','UNIEUR',
				 'YFIEUR','COMPUSD','COMPEUR','GRTUSD','GRTEUR','LRCUSD','LRCEUR','USDTUSD',
				 'USDCUSDT','BTCUSDT','ETHUSDT','XRPUSDT','EURTEUR','EURTUSD','MANAUSD',
				 'MATICUSD','MATICEUR','SUSHIUSD','SUSHIEUR','CHZUSD','CHZEUR','ENJUSD','ENJEUR',
				 'HBAREUR','ALPHAUSD','ALPHAEUR','AXSUSD','AXSEUR','FTTUSD','FTTEUR','SANDUSD',
				 'STORJUSD','STORJEUR','ADAUSD','ADAEUR','FETUSD','FETEUR','SKLUSD','SKLEUR',
				 'CELEUR','SLPUSD','SLPEUR','SXPUSD','SXPEUR','SGBUSD','SGBEUR','AVAXUSD','AVAXEUR',
				 'DYDXEUR','FTMUSD','FTMEUR','SHIBUSD','SHIBEUR','AMPUSD','AMPEUR','ENSUSD','ENSEUR',
				 'GALAEUR','PERPUSD','PERPEUR','CTSIUSD','CTSIEUR','CVXUSD','CVXEUR','IMXUSD',
				 'NEXOUSD','NEXOEUR','ANTUSD','ANTEUR','GODSUSD','GODSEUR','RADUSD','RADEUR','BANDUSD',
				 'INJUSD','INJEUR','RLYUSD','RLYEUR','RNDRUSD','RNDREUR','VEGAUSD','VEGAEUR','1INCHUSD',
				 'SOLUSD','SOLEUR','APEUSD','APEEUR','MPLUSD','MPLEUR','DOTUSD','DOTEUR','NEARUSD','NEAREUR']

